### ISSUE TITLE
Uses <context:component-scan base-package="com.cebedo.pmsys" /> scan but still declares beans in the appServlet/servlet-context.xm

### ISSUE THREAD

**Issue by reylibutan** [VicCebedo/PracticeRepo#1]
Dili ko sure pero murag redundant nga nag gamit ka component-scan nya gideclare japun nimo manually imong beans haha

**Comment by VicCebedo** [comment]
para manas @controllers ang component scan, di ko sure. i-try nakog remove hmmm @reylibutan

**Comment by VicCebedo** [comment]
maguba oy, hahahaha XML man akong gamit, wa ko nag annotate2x, hahaha CLOOOSEEED. HAHA @reylibutan

**Comment by reylibutan** [comment]
Tanan man gud na iyang iscan haha, naa man kay @Service, @Repository. Dapat muwork nga wala na ang bean declarations.

**Comment by VicCebedo** [comment]
sige suwayan nako ugma, haha @reylibutan

**Comment by VicCebedo** [comment]
di xa mugana. mu-gana akong controllers kay gi-autowire man nako akong mga services. pero sa sud sa services ug dao, wa ko nag autowire2x. xml ako gamit kay naa mansan uban beans dependent sa other beans. hmmm awa akong JMS listeners nigamit sad ug beans, bahala di xa service ug repo. hmmm @reylibutan

**Comment by reylibutan** [comment]
Murag dugay na ni, pero pwede man ka mag @Autowire japun bisan sud sa imong *Listener. anywhere man ka maka autowire haha

**Comment by VicCebedo** [comment]
oh shadap rey hahaha limpyo na kaau na akong servlet context xml, naka-map na tanan, ayaw nako labda hahaha
